version: "3"

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    restart: always
    env_file:
      - ./config/mongo/.env
    volumes:
      - sicat-mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - ./config/mongo-express/.env
    depends_on:
      - mongo

volumes:
  sicat-mongo-volume:
